### ISSUE TITLE
Lab 1 Feedback

### ISSUE THREAD

**Issue by alanarnholt** [STT3851-Fall2019/lab1-bobbyregan#1]
@bobbyregan 

LIne 171 of the Rmd document has the wrong footnote....it should be

^[Use the argument `dpi = 96` inside `include_graphics()`.] 

Then you need to follow the footnote by having a code chunk like:

```{r, label = "ig", echo = FALSE, fig.cap = "Using `knitr::include_graphics()`"}
knitr::include_graphics("./JPG/YourFileName.jpeg", dpi = 96)
```

The rest looks great.

**Comment by bobbyregan** [comment]
I have fixed this issue @alanarnholt

**Comment by alanarnholt** [comment]
@bobbyregan 

Your line 171 has: To display the saved file as shown in Figure `\@ref(fig:fig1)`

But you have named your figure with the label argument in the code chunk on line 173 "ig"...

Change line 171 to: To display the saved file as shown in Figure` \@ref(fig:ig)`

and then the `??` hyperlink will turn into 1.1.

**Comment by bobbyregan** [comment]
@alanarnholt Okay I think Ive got it now

**Comment by alanarnholt** [comment]
@bobbyregan looks good now will close the issue.
